#!/usr/bin/env bash

echo "Starting bootstrapping"

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Homebrew if Homebrew isn't installed
if test ! $(which brew); then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew
brew update

# Installing pyenv dependencies to improve script performance
brew install openssl readline sqlite3 xz zlib

PACKAGES=(
    git
    markdown
    npm
    pyenv
    pyenv-virtualenv
    vim
)

echo "Installing packages..."
brew install ${PACKAGES[@]}

echo "Cleaning up..."
brew cleanup

echo "Installing Python..."
pyenv install 3.9.13
pyenv global 3.9.13

echo "Installing cask..."
brew install caskroom/cask/brew-cask

CASKS=(
    google-chrome
    google-drive
    iterm2
    spectacle
)

echo "Installing cask apps..."
brew install ${CASKS[@]} --cask
brew install thefuck
brew install zsh-autosuggestions

echo "Setting up pyenv and virtualenv inits..."
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

echo "Installing global aliases..."
alias -g whatsmyip="curl ifconfig.me"
alias -g goback="cd .."
alias -g rss="exec "$SHELL""
alias -g awake="caffeinate -d"

eval $(thefuck --alias oops)

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PS1='($(pyenv version-name))'$PS1

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

exec "$SHELL"

echo "Bootstrapping complete!"
